server:
  port: 9192

  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - path=/employee/**
            filters:
              - args:
                  name: employee-service
                  fallbackuri: forward:/employeeServiceFallback

          - id: department-service
            uri: lb://department-service
            predicates:
              - path=/department/**

            filters:
              - name:  CircuitBreaker
                args:
                  name: department-service
                  fallbackuri: forward:/departmentServiceFallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/