server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/

#Making Zipkin to publish all matrix 100%
management:
  tracing:
    sampling:
      probability: 1.0